/**
 * Message Keys for Samanin Platform
 * Used for internationalization (i18n) across the application
 * Following README_API.md guidelines - backend code must use these keys instead of hardcoded text
 */

export const MessageKeys = {
  // Authentication Success Messages
  REGISTRATION_SUCCESS: 'auth.REGISTRATION_SUCCESS',
  LOGIN_SUCCESS: 'auth.LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'auth.LOGOUT_SUCCESS',

  // Authentication Error Messages
  EMAIL_ALREADY_EXISTS: 'auth.EMAIL_ALREADY_EXISTS',
  PASSWORD_CONFIRMATION_MISMATCH: 'auth.PASSWORD_CONFIRMATION_MISMATCH',
  PASSWORD_POLICY_VIOLATION: 'auth.PASSWORD_POLICY_VIOLATION',
  REGISTRATION_SUCCESS_EMAIL_DELAYED: 'auth.REGISTRATION_SUCCESS_EMAIL_DELAYED',
  INVALID_CREDENTIALS: 'auth.INVALID_CREDENTIALS',
  PASSWORD_MISMATCH: 'auth.PASSWORD_MISMATCH',
  WEAK_PASSWORD: 'auth.WEAK_PASSWORD',
  INVALID_EMAIL_FORMAT: 'auth.INVALID_EMAIL_FORMAT',
  EMAIL_VERIFICATION_REQUIRED: 'auth.EMAIL_VERIFICATION_REQUIRED',
  ACCOUNT_LOCKED: 'auth.ACCOUNT_LOCKED',
  RATE_LIMIT_EXCEEDED: 'auth.RATE_LIMIT_EXCEEDED',
  SESSION_EXPIRED: 'auth.SESSION_EXPIRED',
  INVALID_RESET_TOKEN: 'auth.INVALID_RESET_TOKEN',
  EXPIRED_RESET_TOKEN: 'auth.EXPIRED_RESET_TOKEN',
  PASSWORD_RESET_LINK_SENT: 'auth.PASSWORD_RESET_LINK_SENT',
  PASSWORD_RESET_SUCCESS: 'auth.PASSWORD_RESET_SUCCESS',

  // Validation Error Messages
  FIELD_REQUIRED: 'validation.FIELD_REQUIRED',
  REQUIRED_FIELDS_MISSING: 'validation.REQUIRED_FIELDS_MISSING',
  INVALID_INPUT: 'validation.INVALID_INPUT',
  COMPANY_NAME_LENGTH: 'validation.COMPANY_NAME_LENGTH',
  FIELD_TOO_SHORT: 'validation.FIELD_TOO_SHORT',
  FIELD_TOO_LONG: 'validation.FIELD_TOO_LONG',
  INVALID_FORMAT: 'validation.INVALID_FORMAT',

  // User Error Messages
  USER_NOT_FOUND: 'errors.USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'errors.USER_ALREADY_EXISTS',

  // Category Management Messages (?, ?, ?)
  CATEGORY_CREATED: 'categories.CATEGORY_CREATED',
  CATEGORY_NAME_EXISTS: 'categories.CATEGORY_NAME_EXISTS',
  CATEGORY_NAME_REQUIRED: 'categories.CATEGORY_NAME_REQUIRED',
  CATEGORY_NAME_TOO_LONG: 'categories.CATEGORY_NAME_TOO_LONG',
  CATEGORY_DESCRIPTION_TOO_LONG: 'categories.CATEGORY_DESCRIPTION_TOO_LONG',
  CATEGORY_PERMISSION_DENIED: 'categories.PERMISSION_DENIED',
  CATEGORY_INVALID_INPUT: 'categories.INVALID_INPUT',
  CATEGORIES_RETRIEVED: 'categories.CATEGORIES_RETRIEVED',
  CATEGORIES_NOT_FOUND: 'categories.CATEGORIES_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'categories.CATEGORY_NOT_FOUND',
  CATEGORY_UPDATED: 'categories.CATEGORY_UPDATED',
  CATEGORY_UPDATE_FAILED: 'categories.CATEGORY_UPDATE_FAILED',
  CATEGORY_DELETED: 'categories.CATEGORY_DELETED',
  CATEGORY_DELETE_FAILED: 'categories.CATEGORY_DELETE_FAILED',
  CATEGORY_HAS_ASSOCIATED_ITEMS: 'categories.CATEGORY_HAS_ASSOCIATED_ITEMS',
  ITEMS_COUNT_RETRIEVED: 'categories.ITEMS_COUNT_RETRIEVED',

  // Tenant Error Messages
  TENANT_NOT_FOUND: 'errors.TENANT_NOT_FOUND',
  TENANT_CREATION_FAILED: 'errors.TENANT_CREATION_FAILED',

  // System Error Messages
  INTERNAL_SERVER_ERROR: 'errors.INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'errors.SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'errors.DATABASE_ERROR',
  EMAIL_SERVICE_ERROR: 'errors.EMAIL_SERVICE_ERROR',
  DATABASE_CONNECTION_ERROR: 'errors.DATABASE_CONNECTION_ERROR',
  LOGIN_TEMPORARILY_UNAVAILABLE: 'errors.LOGIN_TEMPORARILY_UNAVAILABLE',

  // Business Rule Violations
  INVALID_LANGUAGE_SELECTION: 'business.INVALID_LANGUAGE_SELECTION',
  INVALID_LOCALE_SELECTION: 'business.INVALID_LOCALE_SELECTION',
  REGISTRATION_TEMPORARILY_UNAVAILABLE:
    'business.REGISTRATION_TEMPORARILY_UNAVAILABLE',

  // Email Related Messages
  EMAIL_SENT_SUCCESS: 'email.SENT_SUCCESS',
  EMAIL_DELIVERY_DELAYED: 'email.DELIVERY_DELAYED',
  VERIFICATION_EMAIL_SENT: 'email.VERIFICATION_SENT',

  // Email Template Messages - Verification Email
  EMAIL_VERIFICATION_SUBJECT: 'email.VERIFICATION_SUBJECT',
  EMAIL_VERIFICATION_WELCOME: 'email.VERIFICATION_WELCOME',
  EMAIL_VERIFICATION_HELLO: 'email.VERIFICATION_HELLO',
  EMAIL_VERIFICATION_THANK_YOU: 'email.VERIFICATION_THANK_YOU',
  EMAIL_VERIFICATION_BUTTON_TEXT: 'email.VERIFICATION_BUTTON_TEXT',
  EMAIL_VERIFICATION_ALTERNATIVE_TEXT: 'email.VERIFICATION_ALTERNATIVE_TEXT',
  EMAIL_VERIFICATION_EXPIRY_NOTE: 'email.VERIFICATION_EXPIRY_NOTE',
  EMAIL_VERIFICATION_IGNORE_NOTE: 'email.VERIFICATION_IGNORE_NOTE',
  EMAIL_VERIFICATION_FOOTER: 'email.VERIFICATION_FOOTER',

  // Email Template Messages - Password Reset Email
  EMAIL_RESET_SUBJECT: 'email.RESET_SUBJECT',
  EMAIL_RESET_HEADER: 'email.RESET_HEADER',
  EMAIL_RESET_HELLO: 'email.RESET_HELLO',
  EMAIL_RESET_DESCRIPTION: 'email.RESET_DESCRIPTION',
  EMAIL_RESET_BUTTON_TEXT: 'email.RESET_BUTTON_TEXT',
  EMAIL_RESET_ALTERNATIVE_TEXT: 'email.RESET_ALTERNATIVE_TEXT',
  EMAIL_RESET_IMPORTANT_TITLE: 'email.RESET_IMPORTANT_TITLE',
  EMAIL_RESET_EXPIRY_NOTE: 'email.RESET_EXPIRY_NOTE',
  EMAIL_RESET_SINGLE_USE_NOTE: 'email.RESET_SINGLE_USE_NOTE',
  EMAIL_RESET_IGNORE_NOTE: 'email.RESET_IGNORE_NOTE',
  EMAIL_RESET_SECURITY_TITLE: 'email.RESET_SECURITY_TITLE',
  EMAIL_RESET_SECURITY_LENGTH: 'email.RESET_SECURITY_LENGTH',
  EMAIL_RESET_SECURITY_MIXED_CASE: 'email.RESET_SECURITY_MIXED_CASE',
  EMAIL_RESET_SECURITY_NUMBERS: 'email.RESET_SECURITY_NUMBERS',
  EMAIL_RESET_FOOTER: 'email.RESET_FOOTER',
  EMAIL_RESET_SUPPORT_NOTE: 'email.RESET_SUPPORT_NOTE',

  // Email Verification Messages
  EMAIL_VERIFIED_SUCCESS: 'auth.EMAIL_VERIFIED_SUCCESS',
  INVALID_VERIFICATION_TOKEN: 'auth.INVALID_VERIFICATION_TOKEN',
  EXPIRED_VERIFICATION_TOKEN: 'auth.EXPIRED_VERIFICATION_TOKEN',
  EMAIL_ALREADY_VERIFIED: 'auth.EMAIL_ALREADY_VERIFIED',
  TOO_MANY_VERIFICATION_ATTEMPTS: 'auth.TOO_MANY_VERIFICATION_ATTEMPTS',
  VERIFICATION_EMAIL_SENT_SUCCESS: 'auth.VERIFICATION_EMAIL_SENT',
  VERIFICATION_TEMPORARILY_UNAVAILABLE:
    'errors.VERIFICATION_TEMPORARILY_UNAVAILABLE',

  // Dashboard Messages
  DASHBOARD_DATA_SUCCESS: 'dashboard.DASHBOARD_DATA_SUCCESS',
  DASHBOARD_WELCOME: 'dashboard.DASHBOARD_WELCOME',
  DASHBOARD_TENANT_INACTIVE: 'dashboard.TENANT_INACTIVE',
  DASHBOARD_ACCESS_DENIED: 'dashboard.ACCESS_DENIED',
  DASHBOARD_DATA_ERROR: 'dashboard.DATA_ERROR',

  // Locale Formatting Messages
  FORMATTING_CONFIG_SUCCESS: 'locale.FORMATTING_CONFIG_SUCCESS',
  FORMATTING_CONFIG_ERROR: 'locale.FORMATTING_CONFIG_ERROR',

  // User Management Messages (?)
  USER_CREATED_SUCCESS: 'users.USER_CREATED_SUCCESS',
  USER_CREATION_FAILED: 'users.USER_CREATION_FAILED',
  EMAIL_ALREADY_EXISTS_IN_TENANT: 'users.EMAIL_ALREADY_EXISTS_IN_TENANT',
  INVALID_ROLE_ASSIGNMENT: 'users.INVALID_ROLE_ASSIGNMENT',
  INSUFFICIENT_PERMISSIONS: 'users.INSUFFICIENT_PERMISSIONS',
  ROLE_ASSIGNMENT_RESTRICTED: 'users.ROLE_ASSIGNMENT_RESTRICTED',
  INVALID_PHONE_NUMBER_FORMAT: 'users.INVALID_PHONE_NUMBER_FORMAT',
  WELCOME_EMAIL_FAILED: 'users.WELCOME_EMAIL_FAILED',
  ROLES_RETRIEVED_SUCCESS: 'users.ROLES_RETRIEVED_SUCCESS',

  // User List Messages (?)
  USERS_LIST_SUCCESS: 'users.USERS_LIST_SUCCESS',
  INVALID_FILTER_CRITERIA: 'users.INVALID_FILTER_CRITERIA',
  INVALID_SORT_FIELD: 'users.INVALID_SORT_FIELD',
  INVALID_PAGE_PARAMETERS: 'users.INVALID_PAGE_PARAMETERS',

  // User Profile Edit Messages (?)
  USER_UPDATED_SUCCESS: 'users.USER_UPDATED_SUCCESS',
  USER_UPDATE_FAILED: 'users.USER_UPDATE_FAILED',
  CANNOT_EDIT_HIGHER_PRIVILEGE_USER: 'users.CANNOT_EDIT_HIGHER_PRIVILEGE_USER',
  CANNOT_MODIFY_OWN_ROLE: 'users.CANNOT_MODIFY_OWN_ROLE',
  CANNOT_MODIFY_OWN_STATUS: 'users.CANNOT_MODIFY_OWN_STATUS',
  INVALID_USER_STATUS: 'users.INVALID_USER_STATUS',
  EMAIL_IMMUTABLE: 'users.EMAIL_IMMUTABLE',
  USER_STATUS_CHANGED: 'users.USER_STATUS_CHANGED',
  USER_ROLE_CHANGED: 'users.USER_ROLE_CHANGED',
  NO_CHANGES_DETECTED: 'users.NO_CHANGES_DETECTED',

  // ? - Role-Based Login Messages
  ACCOUNT_DEACTIVATED: 'auth.ACCOUNT_DEACTIVATED',
  TENANT_SUSPENDED: 'errors.TENANT_SUSPENDED',
  TENANT_INACTIVE: 'errors.TENANT_INACTIVE',
  PASSWORD_RESET_REQUIRED: 'auth.PASSWORD_RESET_REQUIRED',

  // Profile Update Email Messages
  EMAIL_PROFILE_UPDATE_SUBJECT: 'email.PROFILE_UPDATE_SUBJECT',
  EMAIL_PROFILE_UPDATE_HEADER: 'email.PROFILE_UPDATE_HEADER',
  EMAIL_PROFILE_UPDATE_HELLO: 'email.PROFILE_UPDATE_HELLO',
  EMAIL_PROFILE_UPDATE_NOTIFICATION: 'email.PROFILE_UPDATE_NOTIFICATION',
  EMAIL_PROFILE_UPDATE_CHANGES_TITLE: 'email.PROFILE_UPDATE_CHANGES_TITLE',
  EMAIL_PROFILE_UPDATE_ROLE_CHANGED: 'email.PROFILE_UPDATE_ROLE_CHANGED',
  EMAIL_PROFILE_UPDATE_STATUS_CHANGED: 'email.PROFILE_UPDATE_STATUS_CHANGED',
  EMAIL_PROFILE_UPDATE_CONTACT_SUPPORT: 'email.PROFILE_UPDATE_CONTACT_SUPPORT',
  EMAIL_PROFILE_UPDATE_FOOTER: 'email.PROFILE_UPDATE_FOOTER',

  // Welcome Email Messages
  EMAIL_WELCOME_SUBJECT: 'email.WELCOME_SUBJECT',
  EMAIL_WELCOME_HEADER: 'email.WELCOME_HEADER',
  EMAIL_WELCOME_HELLO: 'email.WELCOME_HELLO',
  EMAIL_WELCOME_ACCOUNT_CREATED: 'email.WELCOME_ACCOUNT_CREATED',
  EMAIL_WELCOME_LOGIN_INSTRUCTIONS: 'email.WELCOME_LOGIN_INSTRUCTIONS',
  EMAIL_WELCOME_LOGIN_BUTTON_TEXT: 'email.WELCOME_LOGIN_BUTTON_TEXT',
  EMAIL_WELCOME_CREDENTIALS_TITLE: 'email.WELCOME_CREDENTIALS_TITLE',
  EMAIL_WELCOME_EMAIL_LABEL: 'email.WELCOME_EMAIL_LABEL',
  EMAIL_WELCOME_PASSWORD_LABEL: 'email.WELCOME_PASSWORD_LABEL',
  EMAIL_WELCOME_CHANGE_PASSWORD_NOTE: 'email.WELCOME_CHANGE_PASSWORD_NOTE',
  EMAIL_WELCOME_SUPPORT_NOTE: 'email.WELCOME_SUPPORT_NOTE',
  EMAIL_WELCOME_FOOTER: 'email.WELCOME_FOOTER',

  // ? - Password Reset Messages
  ADMIN_PASSWORD_RESET_SUCCESS: 'users.PASSWORD_RESET_SUCCESS',
  PASSWORD_RESET_FAILED: 'users.PASSWORD_RESET_FAILED',
  PASSWORD_RESET_EMAIL_FAILED: 'users.PASSWORD_RESET_EMAIL_FAILED',
  PASSWORD_RESET_RATE_LIMITED: 'users.PASSWORD_RESET_RATE_LIMITED',
  PASSWORD_RESET_SELF_ATTEMPT: 'users.PASSWORD_RESET_SELF_ATTEMPT',
  PASSWORD_RESET_USER_DEACTIVATED: 'users.PASSWORD_RESET_USER_DEACTIVATED',
  PASSWORD_RESET_INSUFFICIENT_PERMISSIONS:
    'users.PASSWORD_RESET_INSUFFICIENT_PERMISSIONS',

  // ? - Admin Password Reset Email Messages
  EMAIL_ADMIN_RESET_SUBJECT: 'email.ADMIN_RESET_SUBJECT',
  EMAIL_ADMIN_RESET_HEADER: 'email.ADMIN_RESET_HEADER',
  EMAIL_ADMIN_RESET_HELLO: 'email.ADMIN_RESET_HELLO',
  EMAIL_ADMIN_RESET_NOTIFICATION: 'email.ADMIN_RESET_NOTIFICATION',
  EMAIL_ADMIN_RESET_TEMPORARY_PASSWORD: 'email.ADMIN_RESET_TEMPORARY_PASSWORD',
  EMAIL_ADMIN_RESET_LOGIN_INSTRUCTIONS: 'email.ADMIN_RESET_LOGIN_INSTRUCTIONS',
  EMAIL_ADMIN_RESET_CHANGE_PASSWORD_NOTE:
    'email.ADMIN_RESET_CHANGE_PASSWORD_NOTE',
  EMAIL_ADMIN_RESET_LINK_DESCRIPTION: 'email.ADMIN_RESET_LINK_DESCRIPTION',
  EMAIL_ADMIN_RESET_BUTTON_TEXT: 'email.ADMIN_RESET_BUTTON_TEXT',
  EMAIL_ADMIN_RESET_EXPIRY_NOTE: 'email.ADMIN_RESET_EXPIRY_NOTE',
  EMAIL_ADMIN_RESET_SECURITY_NOTE: 'email.ADMIN_RESET_SECURITY_NOTE',
  EMAIL_ADMIN_RESET_FOOTER: 'email.ADMIN_RESET_FOOTER',

  // ? - Self-Service Profile Management Messages
  PROFILE_RETRIEVED_SUCCESS: 'users.PROFILE_RETRIEVED',
  PROFILE_UPDATED_SUCCESS: 'users.PROFILE_UPDATED',
  PROFILE_UPDATE_FAILED: 'users.PROFILE_UPDATE_FAILED',
  PASSWORD_CHANGED_SUCCESS: 'users.PASSWORD_CHANGED',
  PASSWORD_CHANGE_FAILED: 'users.PASSWORD_CHANGE_FAILED',
  CURRENT_PASSWORD_INCORRECT: 'users.CURRENT_PASSWORD_INCORRECT',
  SESSIONS_RETRIEVED_SUCCESS: 'users.SESSIONS_RETRIEVED',
  SESSION_TERMINATED_SUCCESS: 'users.SESSION_TERMINATED',
  SESSION_TERMINATION_FAILED: 'users.SESSION_TERMINATION_FAILED',
  SESSION_NOT_FOUND: 'users.SESSION_NOT_FOUND',
  CANNOT_TERMINATE_CURRENT_SESSION: 'users.CANNOT_TERMINATE_CURRENT_SESSION',
  ACTIVITY_RETRIEVED_SUCCESS: 'users.ACTIVITY_RETRIEVED',
  ACTIVITY_RETRIEVAL_FAILED: 'users.ACTIVITY_RETRIEVAL_FAILED',

  // Activity Type Keys for i18n
  ACTIVITY_TYPE_ACTIVITY_VIEWED: 'audit.actions.activity_viewed',
  ACTIVITY_TYPE_PROFILE_VIEWED: 'audit.actions.profile_viewed',
  ACTIVITY_TYPE_INVENTORY_LIST_VIEWED: 'audit.actions.inventory_list_viewed',
  ACTIVITY_TYPE_LOGIN_SUCCESS: 'audit.actions.login_success',
  ACTIVITY_TYPE_LOGIN_FAILED: 'audit.actions.login_failed',
  ACTIVITY_TYPE_LOGOUT: 'audit.actions.logout',
  ACTIVITY_TYPE_PASSWORD_CHANGED: 'audit.actions.password_changed',
  ACTIVITY_TYPE_PROFILE_UPDATED: 'audit.actions.profile_updated',
  ACTIVITY_TYPE_USER_CREATED: 'audit.actions.user_created',
  ACTIVITY_TYPE_USER_UPDATED: 'audit.actions.user_updated',
  ACTIVITY_TYPE_USER_DELETED: 'audit.actions.user_deleted',
  ACTIVITY_TYPE_USER_STATUS_CHANGED: 'audit.actions.user_status_changed',
  ACTIVITY_TYPE_USER_ROLE_CHANGED: 'audit.actions.user_role_changed',
  ACTIVITY_TYPE_CATEGORY_CREATED: 'audit.actions.category_created',
  ACTIVITY_TYPE_CATEGORY_UPDATED: 'audit.actions.category_updated',
  ACTIVITY_TYPE_CATEGORY_DELETED: 'audit.actions.category_deleted',
  ACTIVITY_TYPE_INVENTORY_ITEM_CREATED: 'audit.actions.inventory_item_created',
  ACTIVITY_TYPE_INVENTORY_ITEM_UPDATED: 'audit.actions.inventory_item_updated',
  ACTIVITY_TYPE_INVENTORY_ITEM_DELETED: 'audit.actions.inventory_item_deleted',
  ACTIVITY_TYPE_INVENTORY_ITEM_VIEWED: 'audit.actions.inventory_item_viewed',
  ACTIVITY_TYPE_AUDIT_LOGS_VIEWED: 'audit.actions.audit_logs_viewed',
  ACTIVITY_TYPE_PERMISSION_GRANTED: 'audit.actions.permission_granted',
  ACTIVITY_TYPE_PERMISSION_DENIED: 'audit.actions.permission_denied',

  // ? - Audit Trail Management Messages
  AUDIT_LOGS_RETRIEVED_SUCCESS: 'audit.LOGS_RETRIEVED',
  AUDIT_LOGS_RETRIEVAL_FAILED: 'audit.LOGS_RETRIEVAL_FAILED',
  AUDIT_EXPORT_INITIATED_SUCCESS: 'audit.EXPORT_INITIATED',
  AUDIT_EXPORT_INITIATION_FAILED: 'audit.EXPORT_INITIATION_FAILED',
  AUDIT_EXPORT_COMPLETED_SUCCESS: 'audit.EXPORT_COMPLETED',
  AUDIT_EXPORT_FAILED: 'audit.EXPORT_FAILED',
  AUDIT_ACCESS_DENIED: 'audit.ACCESS_DENIED',
  AUDIT_INVALID_DATE_RANGE: 'audit.INVALID_DATE_RANGE',
  AUDIT_INVALID_PARAMETERS: 'audit.INVALID_PARAMETERS',
  AUDIT_EXPORT_TOO_LARGE: 'audit.EXPORT_TOO_LARGE',
  AUDIT_EXPORT_NOT_FOUND: 'audit.EXPORT_NOT_FOUND',
  AUDIT_EXPORT_NOT_READY: 'audit.EXPORT_NOT_READY',
  AUDIT_EXPORT_EXPIRED: 'audit.EXPORT_EXPIRED',

  // ? - Permission Management Messages
  PERMISSIONS_RETRIEVED_SUCCESS: 'permissions.PERMISSIONS_RETRIEVED',
  PERMISSIONS_RETRIEVAL_FAILED: 'permissions.PERMISSIONS_RETRIEVAL_FAILED',
  ROLE_PERMISSIONS_RETRIEVED_SUCCESS: 'permissions.ROLE_PERMISSIONS_RETRIEVED',
  ROLE_PERMISSIONS_RETRIEVAL_FAILED:
    'permissions.ROLE_PERMISSIONS_RETRIEVAL_FAILED',
  ROLE_PERMISSIONS_UPDATED_SUCCESS: 'permissions.ROLE_PERMISSIONS_UPDATED',
  ROLE_PERMISSIONS_UPDATE_FAILED: 'permissions.ROLE_PERMISSIONS_UPDATE_FAILED',
  PERMISSION_CHECK_COMPLETED: 'permissions.PERMISSION_CHECK_COMPLETED',
  PERMISSION_CHECK_FAILED: 'permissions.PERMISSION_CHECK_FAILED',
  PERMISSION_AUDIT_RETRIEVED_SUCCESS: 'permissions.PERMISSION_AUDIT_RETRIEVED',
  PERMISSION_AUDIT_RETRIEVAL_FAILED:
    'permissions.PERMISSION_AUDIT_RETRIEVAL_FAILED',
  PERMISSION_DENIED: 'permissions.PERMISSION_DENIED',
  INSUFFICIENT_ROLE_PRIVILEGES: 'permissions.INSUFFICIENT_ROLE_PRIVILEGES',
  INVALID_PERMISSION_REQUEST: 'permissions.INVALID_PERMISSION_REQUEST',
  ROLE_NOT_FOUND: 'permissions.ROLE_NOT_FOUND',
  PERMISSION_NOT_FOUND: 'permissions.PERMISSION_NOT_FOUND',
  PRIVILEGE_ESCALATION_ATTEMPT: 'permissions.PRIVILEGE_ESCALATION_ATTEMPT',
  PERMISSION_SYSTEM_ERROR: 'permissions.PERMISSION_SYSTEM_ERROR',

  // ? - User Account Deactivation and Reactivation Messages
  USER_STATUS_CHANGED_SUCCESS: 'success.USER_STATUS_CHANGED',
  BULK_STATUS_CHANGE_COMPLETED: 'success.BULK_STATUS_CHANGE_COMPLETED',
  USER_STATUS_CHANGE_FAILED: 'users.USER_STATUS_CHANGE_FAILED',
  BULK_STATUS_CHANGE_FAILED: 'users.BULK_STATUS_CHANGE_FAILED',
  CANNOT_DEACTIVATE_SELF: 'users.CANNOT_DEACTIVATE_SELF',
  CANNOT_DEACTIVATE_LAST_ADMIN: 'users.CANNOT_DEACTIVATE_LAST_ADMIN',
  INSUFFICIENT_PERMISSIONS_STATUS_CHANGE:
    'users.INSUFFICIENT_PERMISSIONS_STATUS_CHANGE',
  USER_HAS_ACTIVE_OPERATIONS: 'users.USER_HAS_ACTIVE_OPERATIONS',
  INVALID_STATUS_TRANSITION: 'users.INVALID_STATUS_TRANSITION',
  BULK_OPERATION_LIMIT_EXCEEDED: 'users.BULK_OPERATION_LIMIT_EXCEEDED',
  STATUS_CHANGE_NOTIFICATION_FAILED: 'users.STATUS_CHANGE_NOTIFICATION_FAILED',
  SESSION_TERMINATION_PARTIAL_FAILURE:
    'users.SESSION_TERMINATION_PARTIAL_FAILURE',

  // ? - Status Change Email Messages
  EMAIL_STATUS_CHANGE_SUBJECT: 'email.STATUS_CHANGE_SUBJECT',
  EMAIL_STATUS_DEACTIVATION_HEADER: 'email.STATUS_DEACTIVATION_HEADER',
  EMAIL_STATUS_REACTIVATION_HEADER: 'email.STATUS_REACTIVATION_HEADER',
  EMAIL_STATUS_CHANGE_HELLO: 'email.STATUS_CHANGE_HELLO',
  EMAIL_DEACTIVATION_NOTIFICATION: 'email.DEACTIVATION_NOTIFICATION',
  EMAIL_REACTIVATION_NOTIFICATION: 'email.REACTIVATION_NOTIFICATION',
  EMAIL_STATUS_CHANGE_REASON: 'email.STATUS_CHANGE_REASON',
  EMAIL_DEACTIVATION_CONSEQUENCES: 'email.DEACTIVATION_CONSEQUENCES',
  EMAIL_REACTIVATION_NEXT_STEPS: 'email.REACTIVATION_NEXT_STEPS',
  EMAIL_STATUS_CHANGE_CONTACT_SUPPORT: 'email.STATUS_CHANGE_CONTACT_SUPPORT',
  EMAIL_STATUS_CHANGE_FOOTER: 'email.STATUS_CHANGE_FOOTER',

  // ? - Inventory Management Messages
  INVENTORY_ITEM_CREATED: 'inventory.INVENTORY_ITEM_CREATED',
  INVENTORY_LIST_RETRIEVED: 'inventory.INVENTORY_LIST_RETRIEVED',
  INVENTORY_ITEM_RETRIEVED: 'inventory.INVENTORY_ITEM_RETRIEVED',
  INVENTORY_ITEM_NOT_FOUND: 'inventory.INVENTORY_ITEM_NOT_FOUND',
  INVENTORY_NAME_EXISTS: 'inventory.INVENTORY_NAME_EXISTS',
  INVENTORY_NAME_REQUIRED: 'inventory.INVENTORY_NAME_REQUIRED',
  INVENTORY_NAME_TOO_LONG: 'inventory.INVENTORY_NAME_TOO_LONG',
  INVENTORY_DESCRIPTION_TOO_LONG: 'inventory.INVENTORY_DESCRIPTION_TOO_LONG',
  INVENTORY_CATEGORY_REQUIRED: 'inventory.INVENTORY_CATEGORY_REQUIRED',
  INVENTORY_ITEM_TYPE_REQUIRED: 'inventory.INVENTORY_ITEM_TYPE_REQUIRED',
  INVENTORY_QUANTITY_INVALID: 'inventory.INVENTORY_QUANTITY_INVALID',
  INVENTORY_QUANTITY_UNIT_TOO_LONG:
    'inventory.INVENTORY_QUANTITY_UNIT_TOO_LONG',
  SERIAL_NUMBER_EXISTS: 'inventory.SERIAL_NUMBER_EXISTS',
  SERIAL_NUMBER_REQUIRED: 'inventory.SERIAL_NUMBER_REQUIRED',
  SERIAL_NUMBER_TOO_LONG: 'inventory.SERIAL_NUMBER_TOO_LONG',
  SERIAL_NUMBER_VALIDATION_RESULT: 'inventory.SERIAL_NUMBER_VALIDATION_RESULT',
  SERIAL_NUMBER_GENERATED: 'inventory.SERIAL_NUMBER_GENERATED',
  SERIAL_NUMBER_GENERATION_FAILED: 'inventory.SERIAL_NUMBER_GENERATION_FAILED',
  INVENTORY_PERMISSION_DENIED: 'inventory.PERMISSION_DENIED',
  INVENTORY_CREATION_FAILED: 'inventory.INVENTORY_CREATION_FAILED',
  INVENTORY_RETRIEVAL_FAILED: 'inventory.INVENTORY_RETRIEVAL_FAILED',

  // ? - Inventory Export Messages
  INVENTORY_ITEM_VIEWED: 'inventory.INVENTORY_ITEM_VIEWED',
  INVENTORY_LIST_VIEWED: 'inventory.INVENTORY_LIST_VIEWED',
  EXPORT_INITIATED: 'inventory.EXPORT_INITIATED',
  EXPORT_COMPLETED: 'inventory.EXPORT_COMPLETED',
  EXPORT_FAILED: 'inventory.EXPORT_FAILED',
  EXPORT_NOT_FOUND: 'inventory.EXPORT_NOT_FOUND',
  EXPORT_EXPIRED: 'inventory.EXPORT_EXPIRED',
  EXPORT_INVALID_FORMAT: 'inventory.EXPORT_INVALID_FORMAT',
  EXPORT_INVALID_TYPE: 'inventory.EXPORT_INVALID_TYPE',
  EXPORT_TOO_LARGE: 'inventory.EXPORT_TOO_LARGE',
  EXPORT_INVALID_ITEMS: 'inventory.EXPORT_INVALID_ITEMS',
  EXPORT_PERMISSION_DENIED: 'inventory.EXPORT_PERMISSION_DENIED',

  // ? - Inventory Item Editing Messages
  ITEM_UPDATED: 'inventory.ITEM_UPDATED',
  EDIT_CONFLICT: 'inventory.EDIT_CONFLICT',
  ITEM_TYPE_LOCKED: 'inventory.ITEM_TYPE_LOCKED',
  STATUS_CHANGED: 'inventory.STATUS_CHANGED',
  INVENTORY_INVALID_STATUS_TRANSITION: 'inventory.INVALID_STATUS_TRANSITION',
  ITEM_ALLOCATED: 'inventory.ITEM_ALLOCATED',
  STATUS_OPTIONS_RETRIEVED: 'inventory.STATUS_OPTIONS_RETRIEVED',
  STATUS_HISTORY_RETRIEVED: 'inventory.STATUS_HISTORY_RETRIEVED',

  // ? - Serialized Item Update Messages
  SERIALIZED_ITEM_UPDATED: 'inventory.SERIALIZED_ITEM_UPDATED',
  SERIAL_NUMBER_CHANGE_WARNING: 'inventory.SERIAL_NUMBER_CHANGE_WARNING',
  SERIAL_NUMBER_CHANGE_RESTRICTED: 'inventory.SERIAL_NUMBER_CHANGE_RESTRICTED',
  SERIAL_NUMBER_CHANGE_CONFIRMATION_REQUIRED:
    'inventory.SERIAL_NUMBER_CHANGE_CONFIRMATION_REQUIRED',
  HISTORICAL_LINK_MAINTAINED: 'inventory.HISTORICAL_LINK_MAINTAINED',
  INVALID_MAINTENANCE_DATES: 'inventory.INVALID_MAINTENANCE_DATES',
  MAINTENANCE_DATE_LOGIC_ERROR: 'inventory.MAINTENANCE_DATE_LOGIC_ERROR',
  CONDITION_NOTES_TOO_LONG: 'inventory.CONDITION_NOTES_TOO_LONG',
  NOT_SERIALIZED_ITEM: 'inventory.NOT_SERIALIZED_ITEM',

  // ? - Quantity Update Messages
  QUANTITY_UPDATED: 'inventory.QUANTITY_UPDATED',
  QUANTITY_BELOW_ALLOCATED: 'inventory.QUANTITY_BELOW_ALLOCATED',
  SIGNIFICANT_QUANTITY_REDUCTION: 'inventory.SIGNIFICANT_QUANTITY_REDUCTION',
  QUANTITY_CHANGE_IMPACT: 'inventory.QUANTITY_CHANGE_IMPACT',
  ALLOCATED_QUANTITY_CONFLICT: 'inventory.ALLOCATED_QUANTITY_CONFLICT',
  NOT_NON_SERIALIZED_ITEM: 'inventory.NOT_NON_SERIALIZED_ITEM',
  QUANTITY_UNIT_TOO_LONG: 'inventory.QUANTITY_UNIT_TOO_LONG',
  CHANGE_REASON_TOO_LONG: 'inventory.CHANGE_REASON_TOO_LONG',

  // ? - Bulk Edit Messages
  BULK_EDIT_COMPLETED: 'inventory.BULK_EDIT_COMPLETED',
  BULK_EDIT_INITIATED: 'inventory.BULK_EDIT_INITIATED',
  BULK_OPERATION_STATUS: 'inventory.BULK_OPERATION_STATUS',
  BULK_OPERATION_NOT_FOUND: 'inventory.BULK_OPERATION_NOT_FOUND',
  BULK_MIXED_ITEM_TYPES: 'inventory.BULK_MIXED_ITEM_TYPES',
  BULK_ITEMS_RESTRICTED: 'inventory.BULK_ITEMS_RESTRICTED',
  BULK_LARGE_OPERATION_WARNING: 'inventory.BULK_LARGE_OPERATION_WARNING',
  BULK_VALIDATION_ERRORS: 'inventory.BULK_VALIDATION_ERRORS',
  BULK_SOME_ITEMS_FAILED: 'inventory.BULK_SOME_ITEMS_FAILED',
  BULK_OPERATION_FAILED: 'inventory.BULK_OPERATION_FAILED',
  BULK_INSUFFICIENT_PERMISSIONS: 'inventory.BULK_INSUFFICIENT_PERMISSIONS',
  BULK_INVALID_ITEM_SELECTION: 'inventory.BULK_INVALID_ITEM_SELECTION',
  BULK_INCOMPATIBLE_OPERATIONS: 'inventory.BULK_INCOMPATIBLE_OPERATIONS',

  // Bulk Operation Error Messages
  BULK_ITEM_NOT_FOUND: 'inventory.BULK_ITEM_NOT_FOUND',
  BULK_CATEGORY_NOT_FOUND: 'inventory.BULK_CATEGORY_NOT_FOUND',
  BULK_GENERAL_ERROR: 'inventory.BULK_GENERAL_ERROR',

  // System Reason Messages
  ITEM_RENTED_OUT: 'inventory.ITEM_RENTED_OUT',
  AUTOMATIC_ASSIGNMENT: 'system.AUTOMATIC_ASSIGNMENT',
  ACCOUNT_LOCKED_REASON: 'auth.ACCOUNT_LOCKED_REASON',
  PASSWORD_RESET_INVALIDATED: 'auth.PASSWORD_RESET_INVALIDATED',
  ADMIN_RESET_INVALIDATED: 'auth.ADMIN_RESET_INVALIDATED',
  DELETION_FAILED_ASSOCIATED_ITEMS:
    'categories.DELETION_FAILED_ASSOCIATED_ITEMS',
  USER_CREATION_ASSIGNMENT: 'users.USER_CREATION_ASSIGNMENT',
} as const;

export type MessageKey = (typeof MessageKeys)[keyof typeof MessageKeys];
